# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a35f58819724ef82e5978ccb3df9327ffa12e188a4e38a76d58fb411e39967da45b68fb388d1d375883e8ff573bba8e15c7fa8db8f1b8555a309cf9f8351eb35

test:
  secret_key_base: deaac1d7dfd9361212c12c10c560e6b829176dab37dc9da255d1bf796af652da457d665d36eda461054b3a0fe86e6a217e121783f501690cd958a32dee679686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
